services:
    senky.api.graphql.context:
        class: senky\api\graphql\context
        arguments:
            - '@dbal.conn'
            - '@config'
            - '@senky.api.graphql.resolver.buffer'
            - '@senky.api.graphql.buffer.forum_buffer'
            - '@senky.api.graphql.buffer.group_buffer'
            - '@senky.api.graphql.buffer.icon_buffer'
            - '@senky.api.graphql.buffer.post_buffer'
            - '@senky.api.graphql.buffer.rank_buffer'
            - '@senky.api.graphql.buffer.smilie_buffer'
            - '@senky.api.graphql.buffer.topic_buffer'
            - '@senky.api.graphql.buffer.user_buffer'
            - '@senky.api.graphql.buffer.user_group_buffer'
            - '%tables.forums%'

    senky.api.graphql.query:
        class: senky\api\graphql\query
        arguments:
            - '@service_container'

    senky.api.graphql.mutation:
        class: senky\api\graphql\mutation
        arguments:
            - '@senky.api.graphql.mutator.topic'


    # ------------ RESOLVERS ------------
    senky.api.graphql.resolver.buffer:
        class: senky\api\graphql\resolver\buffer

    senky.api.graphql.resolver.search:
        class: senky\api\graphql\resolver\search
        arguments:
            - '@config'
            - '@auth'
            - '@dbal.conn'
            - '@user'
            - '@dispatcher'
            - '@content.visibility'
            - '%core.root_path%'
            - '%core.php_ext%'

    # ------------ BUFFERS ------------
    senky.api.graphql.buffer.forum_buffer:
        class: senky\api\graphql\buffer\forum_buffer
        arguments:
            - '@dbal.conn'
            - '@auth'
            - '@config'
            - '%tables.forums%'

    senky.api.graphql.buffer.group_buffer:
        class: senky\api\graphql\buffer\group_buffer
        arguments:
            - '@dbal.conn'
            - '@auth'
            - '@config'
            - '%tables.groups%'

    senky.api.graphql.buffer.icon_buffer:
        class: senky\api\graphql\buffer\icon_buffer
        arguments:
            - '@dbal.conn'
            - '@auth'
            - '@config'
            - '%tables.icons%'

    senky.api.graphql.buffer.post_buffer:
        class: senky\api\graphql\buffer\post_buffer
        arguments:
            - '@dbal.conn'
            - '@auth'
            - '@config'
            - '%tables.posts%'

    senky.api.graphql.buffer.rank_buffer:
        class: senky\api\graphql\buffer\rank_buffer
        arguments:
            - '@dbal.conn'
            - '@auth'
            - '@config'
            - '%tables.ranks%'

    senky.api.graphql.buffer.smilie_buffer:
        class: senky\api\graphql\buffer\smilie_buffer
        arguments:
            - '@dbal.conn'
            - '@auth'
            - '@config'
            - '%tables.smilies%'

    senky.api.graphql.buffer.topic_buffer:
        class: senky\api\graphql\buffer\topic_buffer
        arguments:
            - '@dbal.conn'
            - '@auth'
            - '@config'
            - '%tables.topics%'

    senky.api.graphql.buffer.user_buffer:
        class: senky\api\graphql\buffer\user_buffer
        arguments:
            - '@dbal.conn'
            - '@auth'
            - '@config'
            - '%tables.users%'

    senky.api.graphql.buffer.user_group_buffer:
        class: senky\api\graphql\buffer\user_group_buffer
        arguments:
            - '@dbal.conn'
            - '@auth'
            - '%tables.user_group%'


    # ------------ MUTATORS ------------
    senky.api.graphql.mutator.base:
        class: senky\api\graphql\mutator\base
        abstract: true
        arguments:
            - '@dbal.conn'
            - '@config'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'

    senky.api.graphql.mutator.topic:
        class: senky\api\graphql\mutator\topic
        parent: senky.api.graphql.mutator.base
