services:
    senky.api.graphql.context:
        class: senky\api\graphql\context
        arguments:
            - '@dbal.conn'
            - '@config'
            - '@senky.api.graphql.resolver'
            - '@senky.api.graphql.buffer.forum_buffer'
            - '@senky.api.graphql.buffer.group_buffer'
            - '@senky.api.graphql.buffer.post_buffer'
            - '@senky.api.graphql.buffer.topic_buffer'
            - '@senky.api.graphql.buffer.user_buffer'
            - '@senky.api.graphql.buffer.user_group_buffer'
            - '%tables.forums%'

    senky.api.graphql.resolver:
        class: senky\api\graphql\resolver

    senky.api.graphql.query:
        class: senky\api\graphql\query
        arguments:
            - '@senky.api.graphql.resolver'
            - '@user'

    senky.api.graphql.buffer.forum_buffer:
        class: senky\api\graphql\buffer\forum_buffer
        arguments:
            - '@dbal.conn'
            - '@auth'
            - '@config'
            - '%tables.forums%'

    senky.api.graphql.buffer.group_buffer:
        class: senky\api\graphql\buffer\group_buffer
        arguments:
            - '@dbal.conn'
            - '@auth'
            - '@config'
            - '%tables.groups%'

    senky.api.graphql.buffer.post_buffer:
        class: senky\api\graphql\buffer\post_buffer
        arguments:
            - '@dbal.conn'
            - '@auth'
            - '@config'
            - '%tables.posts%'

    senky.api.graphql.buffer.topic_buffer:
        class: senky\api\graphql\buffer\topic_buffer
        arguments:
            - '@dbal.conn'
            - '@auth'
            - '@config'
            - '%tables.topics%'

    senky.api.graphql.buffer.user_buffer:
        class: senky\api\graphql\buffer\user_buffer
        arguments:
            - '@dbal.conn'
            - '@auth'
            - '@config'
            - '%tables.users%'

    senky.api.graphql.buffer.user_group_buffer:
        class: senky\api\graphql\buffer\user_group_buffer
        arguments:
            - '@dbal.conn'
            - '@auth'
            - '@config'
            - '%tables.user_group%'
