senky_api_graphql:
    path: /api/v0
    defaults: { _controller: senky.api.controller.graphql:handle }
    methods: POST

senky_api_schema:
    path: /api/v0/schema
    defaults: { _controller: senky.api.controller.schema:handle }
    methods: GET

senky_api_preview:
    path: /textformatter.js
    defaults: { _controller: senky.api.controller.textformatter:handle }
    methods: GET
